AllCops:
  NewCops: enable
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Metrics/ClassLength:
  Enabled: false

inherit_from:
  - https://raw.githubusercontent.com/siegy22/dotfiles/1a4eeb8dec27208cc3dc26c3675b5d0a49f00352/rubocop.yml
